export const environment = {
  production: true,
  BASE_URL: "http://localhost:8081/",
  AUTH_URL: "http://localhost:9000/",
  RESOURCE_URL: "http://localhost:8080/",
  authorize_uri: "http://localhost:9000/oauth2/authorize?",
  client_id: "client1",
  redirect_uri: "http://127.0.0.1:4200/authorized",
  scope: "openid",
  response_type: "code",
  response_mode: "form_post",
  code_challenge_method: "S256",
  code_challenge: "D31JLsveEKURXL8x-yvTocCufiwNAScTN5kEsYwDQWI",
  code_verifier: "g4qE6ENmlEHpUxNIv0XrE57LfLjgqG28BRke4XLq6AR",
  token_url: 'http://localhost:9000/oauth2/token',
  grant_type: "authorization_code",
};
