version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - proxy-net
    extra_hosts:
      - 'proxy-net:192.168.238.5'
      - 'proxy-net:192.168.1.103'

networks:
  proxy-net:
    driver: bridge