spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.1.102:32221/article_user_db?sslmode=disable
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

logging:
  level:
    org.springframework.security: trace
    org.springframework.security.oauth2: trace
server:
  port: 9000

init:
  key: n1POc4Ns79wa93l1
