# Defining dev namespace
apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
# Defining Resource quota to use within the namespace dev
apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-quota
  namespace: dev # namespace is used to define for which namespace we are defining this quota
spec:
  hard:
    pods: "100"
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "10"
    limits.memory: 10Gi